### PR TITLE
Parser add tasks

### LINKED ISSUE #4: Implement parser support for adding someday tasks

### PR DESCRIPTION
**Pull request by kabir-plod**
Supports adding somedays and deadlines; events not yet supported. Closes #4 and #25.

### CODE REVIEW

**Comment by kabir-plod** [comment]
Parser supports adding events

**Comment by kabir-plod** [comment]
Added test coverage. Closes #24

**Comment by KnytJC** [comment]
reviewed

**Comment by kelvinnpc** [comment]
reviewed

**Pull request merged**
